 [theme]
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = "500"
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
